Experimenting with hypervolume computations based on https://datacrayon.com/posts/search-and-optimisation/practical-evolutionary-algorithms/hypervolume-indicator/

In [69]:
import numpy as np                   # for multi-dimensional containers
import pandas as pd                  # for DataFrames
import pygmo as pg
import torch

In [70]:
def ZDT1(x):
    f1 = x[0]  # objective 1
    g = 1 + 9 * np.sum(x[1:D] / (D-1))
    h = 1 - np.sqrt(f1 / g)
    f2 = g * h  # objective 2
    
    return [f1, f2]

In [85]:
N = 1
D = 30
solutionVars = []
solutionObj = []
for i in range(N):
    x = np.random.rand(D)
    solutionVars.append(x)
    solutionObj.append(ZDT1(x))

In [86]:
print(f"Design variables:\n {solutionVars[0]}")
print(f"Objective values:\n {solutionObj[0]}")
print(solutionObj)

Design variables:
 [0.72899085 0.58320314 0.5926474  0.99211103 0.6708305  0.35010336
 0.90709076 0.700478   0.30958362 0.93318792 0.8531067  0.16154805
 0.50326912 0.97030297 0.919382   0.92479577 0.35841353 0.45051277
 0.04129493 0.37538081 0.26566901 0.71104565 0.0325592  0.51574419
 0.32250035 0.62043283 0.05290455 0.7782893  0.89584556 0.70993868]
Objective values:
 [0.7289908482098102, 4.00892000550726]
[[0.7289908482098102, 4.00892000550726]]


In [87]:
solutions_df = pd.DataFrame(index=range(N),columns=['f1','f2']).astype(float)
solutions_df.head()

f1  f2
0 NaN NaN

In [88]:
for i in range(N):
    solutions_df.loc[i].f1 = solutionObj[i][0]
    solutions_df.loc[i].f2 = solutionObj[i][1]
        
solutions_df.head()

f1       f2
0  0.728991  4.00892

In [99]:
solutions_df[['f1','f2']].values

array([[0.72899085, 4.00892001]])

In [108]:
x = [[1,3],[3,2]]
r = [5,5]
hyp = pg.hypervolume(x)
hyp.compute(r) / np.prod(r)


0.4

In [89]:
hyp = pg.hypervolume(solutions_df[['f1','f2']].values)

In [96]:
hyp.compute([2, 2])

ValueError: 
function: assert_minimisation
where: /Users/runner/miniforge3/conda-bld/pagmo_1662737413028/work/src/utils/hv_algos/hv_algorithm.cpp, 256
what: Reference point is invalid: another point seems to be outside the reference point boundary, or be equal to it:
 P[0]	= (0.728991, 4.008920)
 R	= (2.000000, 2.000000)



In [91]:
hyp.compute([11, 11]) / np.prod([11, 11])

0.5934334430110103

In [92]:
np.prod([11,11])

121

In [95]:
1 - np.prod(solutions_df[['f1','f2']].values)/np.prod([11,11])

0.9758473884692561

In [84]:
ref_point = [11,11]
solutionObj


[[0.21170824217356743, 4.337908374796963],
 [0.7202403748117212, 3.172017322162057],
 [0.904589994820724, 3.31533769089556],
 [0.13528809749717707, 5.009629664714345],
 [0.7743697759069107, 3.325590849867744]]

In [47]:
sampX = torch.tensor([[ 1.4000, -0.2555,  0.5737],
          [ 0.1806, -1.2344,  1.1003],
          [-0.1094,  0.5419, -0.9551],
          [ 0.8830,  0.0778, -0.6397],
          [ 0.8175, -0.6464,  0.5182],
          [-0.0709,  0.6907, -2.0860],
          [ 0.5955,  1.0229, -0.2274],
          [ 0.7555, -1.5799,  3.5132],
          [-0.8117,  1.2242, -0.1611],
          [ 1.6803, -0.3095,  0.7305],
          [-0.3026,  0.5413, -1.0837],
          [-0.1548, -0.7543,  3.0259],
          [ 0.1076,  0.0716, -1.3297],
          [ 1.0045, -0.6601,  0.5525],
          [-0.4845, -1.3624,  1.3658],
          [ 1.9982,  0.0230, -0.5973]])
sampR = torch.tensor([[ 1.2573,  0.6590, -0.2828],
          [ 1.2892,  1.1650, -2.1206],
          [ 0.8448, -0.2107, -0.3628],
          [ 1.6861,  0.6161, -2.4804],
          [ 0.4265, -0.9463,  3.1731],
          [ 0.1760, -0.2885, -0.2270],
          [ 0.6920,  1.0158, -0.9151],
          [ 0.3762, -0.9244,  4.2004],
          [ 1.0926,  1.8276, -1.8895],
          [ 1.2040,  0.6088, -0.3583],
          [ 0.8632, -0.2110, -0.5059],
          [ 0.3398, -0.5247,  4.1056],
          [ 0.0825, -0.0147, -1.3034],
          [ 1.7539,  0.8847, -2.5063],
          [-0.7149, -1.0610,  0.3214],
          [ 2.3328, -0.4350, -0.0166]])

In [49]:
sampX[4][0]

tensor(0.8175)

In [56]:
q = 16
sol_df = pd.DataFrame(index=range(2*q),columns=['f1','f2','f3']).astype(float)
for i in range(q):
    sol_df.loc[i].f1 = sampX[i][0]
    sol_df.loc[i+q].f1 = sampR[i][0]
    sol_df.loc[i].f2 = sampX[i][1]
    sol_df.loc[i+q].f2 = sampR[i][1]
    sol_df.loc[i].f3 = sampX[i][2]
    sol_df.loc[i+q].f3 = sampR[i][2]
        
sol_df.head()

f1      f2      f3
0  1.4000 -0.2555  0.5737
1  0.1806 -1.2344  1.1003
2 -0.1094  0.5419 -0.9551
3  0.8830  0.0778 -0.6397
4  0.8175 -0.6464  0.5182

In [68]:
from math import inf


objective = torch.tensor([[[ 1.4000, -0.2555,  0.5737],
          [ 0.1806, -1.2344,  1.1003],
          [-0.1094,  0.5419, -0.9551],
          [ 0.8830,  0.0778, -0.6397],
          [ 0.8175, -0.6464,  0.5182],
          [-0.0709,  0.6907, -2.0860],
          [ 0.5955,  1.0229, -0.2274],
          [ 0.7555, -1.5799,  3.5132],
          [-0.8117,  1.2242, -0.1611],
          [ 1.6803, -0.3095,  0.7305],
          [-0.3026,  0.5413, -1.0837],
          [-0.1548, -0.7543,  3.0259],
          [ 0.1076,  0.0716, -1.3297],
          [ 1.0045, -0.6601,  0.5525],
          [-0.4845, -1.3624,  1.3658],
          [ 1.9982,  0.0230, -0.5973]],
        [[ 1.2573,  0.6590, -0.2828],
          [ 1.2892,  1.1650, -2.1206],
          [ 0.8448, -0.2107, -0.3628],
          [ 1.6861,  0.6161, -2.4804],
          [ 0.4265, -0.9463,  3.1731],
          [ 0.1760, -0.2885, -0.2270],
          [ 0.6920,  1.0158, -0.9151],
          [ 0.3762, -0.9244,  4.2004],
          [ 1.0926,  1.8276, -1.8895],
          [ 1.2040,  0.6088, -0.3583],
          [ 0.8632, -0.2110, -0.5059],
          [ 0.3398, -0.5247,  4.1056],
          [ 0.0825, -0.0147, -1.3034],
          [ 1.7539,  0.8847, -2.5063],
          [-0.7149, -1.0610,  0.3214],
          [ 2.3328, -0.4350, -0.0166]]])
lower_bounds = torch.tensor([[[-0.9815,  2.6148, -0.9631],
         [-0.9815,  0.9642,  0.4117],
         [ 0.4580,  0.9642, -0.9631],
         [-0.9815, -0.9764,  1.4772],
         [ 1.6580, -0.9764, -0.9631],
         [ 0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000]],
        [[-0.9815, -0.9764,  3.5490],
         [-0.9815,  2.1130, -0.9631],
         [-0.9815, -0.5243,  1.3315],
         [-0.1888,  0.9520, -0.9631],
         [-0.0863, -0.9764,  1.3315],
         [ 2.3172, -0.9764, -0.9631],
         [-0.1888, -0.5243,  1.0811],
         [-0.0863, -0.9764,  1.0811]]])
ref_point = [-0.9815, -0.9764, -0.9631]


In [114]:
overlap =  torch.tensor([[[[[ 1.4000, -0.2555,  0.5737],
           [ 0.1806, -1.2344,  1.1003],
           [-0.1094,  0.5419, -0.9551],
           [ 0.8830,  0.0778, -0.6397],
           [ 0.8175, -0.6464,  0.5182],
           [-0.0709,  0.6907, -2.0860],
           [ 0.5955,  1.0229, -0.2274],
           [ 0.7555, -1.5799,  3.5132],
           [-0.8117,  1.2242, -0.1611],
           [ 1.6803, -0.3095,  0.7305],
           [-0.3026,  0.5413, -1.0837],
           [-0.1548, -0.7543,  3.0259],
           [ 0.1076,  0.0716, -1.3297],
           [ 1.0045, -0.6601,  0.5525],
           [-0.4845, -1.3624,  1.3658],
           [ 1.9982,  0.0230, -0.5973]]]],
        [[[[ 1.2573,  0.6590, -0.2828],
           [ 1.2892,  1.1650, -2.1206],
           [ 0.8448, -0.2107, -0.3628],
           [ 1.6861,  0.6161, -2.4804],
           [ 0.4265, -0.9463,  3.1731],
           [ 0.1760, -0.2885, -0.2270],
           [ 0.6920,  1.0158, -0.9151],
           [ 0.3762, -0.9244,  4.2004],
           [ 1.0926,  1.8276, -1.8895],
           [ 1.2040,  0.6088, -0.3583],
           [ 0.8632, -0.2110, -0.5059],
           [ 0.3398, -0.5247,  4.1056],
           [ 0.0825, -0.0147, -1.3034],
           [ 1.7539,  0.8847, -2.5063],
           [-0.7149, -1.0610,  0.3214],
           [ 2.3328, -0.4350, -0.0166]]]]])
upper_bounds = torch.tensor([[[    inf,     inf,     inf],
         [    inf,  2.6148,     inf],
         [    inf,  2.6148,  0.4117],
         [    inf,  0.9642,     inf],
         [    inf,  0.9642,  1.4772],
         [ 0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000]],
        [[    inf,     inf,     inf],
         [    inf,     inf,  3.5490],
         [    inf,  2.1130,  3.5490],
         [    inf,  2.1130,  1.3315],
         [    inf, -0.5243,  3.5490],
         [    inf,  0.9520,  1.0811],
         [    inf,  0.9520,  1.3315],
         [    inf, -0.5243,  1.3315]]])

overlap_after =  torch.tensor([[[[[ 1.4000, -0.2555,  0.5737],
           [ 0.1806, -1.2344,  1.1003],
           [-0.1094,  0.5419, -0.9551],
           [ 0.8830,  0.0778, -0.6397],
           [ 0.8175, -0.6464,  0.5182],
           [-0.0709,  0.6907, -2.0860],
           [ 0.5955,  1.0229, -0.2274],
           [ 0.7555, -1.5799,  3.5132],
           [-0.8117,  1.2242, -0.1611],
           [ 1.6803, -0.3095,  0.7305],
           [-0.3026,  0.5413, -1.0837],
           [-0.1548, -0.7543,  3.0259],
           [ 0.1076,  0.0716, -1.3297],
           [ 1.0045, -0.6601,  0.5525],
           [-0.4845, -1.3624,  1.3658],
           [ 1.9982,  0.0230, -0.5973]],
          [[ 1.4000, -0.2555,  0.5737],
           [ 0.1806, -1.2344,  1.1003],
           [-0.1094,  0.5419, -0.9551],
           [ 0.8830,  0.0778, -0.6397],
           [ 0.8175, -0.6464,  0.5182],
           [-0.0709,  0.6907, -2.0860],
           [ 0.5955,  1.0229, -0.2274],
           [ 0.7555, -1.5799,  3.5132],
           [-0.8117,  1.2242, -0.1611],
           [ 1.6803, -0.3095,  0.7305],
           [-0.3026,  0.5413, -1.0837],
           [-0.1548, -0.7543,  3.0259],
           [ 0.1076,  0.0716, -1.3297],
           [ 1.0045, -0.6601,  0.5525],
           [-0.4845, -1.3624,  1.3658],
           [ 1.9982,  0.0230, -0.5973]],
          [[ 1.4000, -0.2555,  0.4117],
           [ 0.1806, -1.2344,  0.4117],
           [-0.1094,  0.5419, -0.9551],
           [ 0.8830,  0.0778, -0.6397],
           [ 0.8175, -0.6464,  0.4117],
           [-0.0709,  0.6907, -2.0860],
           [ 0.5955,  1.0229, -0.2274],
           [ 0.7555, -1.5799,  0.4117],
           [-0.8117,  1.2242, -0.1611],
           [ 1.6803, -0.3095,  0.4117],
           [-0.3026,  0.5413, -1.0837],
           [-0.1548, -0.7543,  0.4117],
           [ 0.1076,  0.0716, -1.3297],
           [ 1.0045, -0.6601,  0.4117],
           [-0.4845, -1.3624,  0.4117],
           [ 1.9982,  0.0230, -0.5973]],
          [[ 1.4000, -0.2555,  0.5737],
           [ 0.1806, -1.2344,  1.1003],
           [-0.1094,  0.5419, -0.9551],
           [ 0.8830,  0.0778, -0.6397],
           [ 0.8175, -0.6464,  0.5182],
           [-0.0709,  0.6907, -2.0860],
           [ 0.5955,  0.9642, -0.2274],
           [ 0.7555, -1.5799,  3.5132],
           [-0.8117,  0.9642, -0.1611],
           [ 1.6803, -0.3095,  0.7305],
           [-0.3026,  0.5413, -1.0837],
           [-0.1548, -0.7543,  3.0259],
           [ 0.1076,  0.0716, -1.3297],
           [ 1.0045, -0.6601,  0.5525],
           [-0.4845, -1.3624,  1.3658],
           [ 1.9982,  0.0230, -0.5973]],
          [[ 1.4000, -0.2555,  0.5737],
           [ 0.1806, -1.2344,  1.1003],
           [-0.1094,  0.5419, -0.9551],
           [ 0.8830,  0.0778, -0.6397],
           [ 0.8175, -0.6464,  0.5182],
           [-0.0709,  0.6907, -2.0860],
           [ 0.5955,  0.9642, -0.2274],
           [ 0.7555, -1.5799,  1.4772],
           [-0.8117,  0.9642, -0.1611],
           [ 1.6803, -0.3095,  0.7305],
           [-0.3026,  0.5413, -1.0837],
           [-0.1548, -0.7543,  1.4772],
           [ 0.1076,  0.0716, -1.3297],
           [ 1.0045, -0.6601,  0.5525],
           [-0.4845, -1.3624,  1.3658],
           [ 1.9982,  0.0230, -0.5973]],
          [[ 0.0000, -0.2555,  0.0000],
           [ 0.0000, -1.2344,  0.0000],
           [-0.1094,  0.0000, -0.9551],
           [ 0.0000,  0.0000, -0.6397],
           [ 0.0000, -0.6464,  0.0000],
           [-0.0709,  0.0000, -2.0860],
           [ 0.0000,  0.0000, -0.2274],
           [ 0.0000, -1.5799,  0.0000],
           [-0.8117,  0.0000, -0.1611],
           [ 0.0000, -0.3095,  0.0000],
           [-0.3026,  0.0000, -1.0837],
           [-0.1548, -0.7543,  0.0000],
           [ 0.0000,  0.0000, -1.3297],
           [ 0.0000, -0.6601,  0.0000],
           [-0.4845, -1.3624,  0.0000],
           [ 0.0000,  0.0000, -0.5973]],
          [[ 0.0000, -0.2555,  0.0000],
           [ 0.0000, -1.2344,  0.0000],
           [-0.1094,  0.0000, -0.9551],
           [ 0.0000,  0.0000, -0.6397],
           [ 0.0000, -0.6464,  0.0000],
           [-0.0709,  0.0000, -2.0860],
           [ 0.0000,  0.0000, -0.2274],
           [ 0.0000, -1.5799,  0.0000],
           [-0.8117,  0.0000, -0.1611],
           [ 0.0000, -0.3095,  0.0000],
           [-0.3026,  0.0000, -1.0837],
           [-0.1548, -0.7543,  0.0000],
           [ 0.0000,  0.0000, -1.3297],
           [ 0.0000, -0.6601,  0.0000],
           [-0.4845, -1.3624,  0.0000],
           [ 0.0000,  0.0000, -0.5973]],
          [[ 0.0000, -0.2555,  0.0000],
           [ 0.0000, -1.2344,  0.0000],
           [-0.1094,  0.0000, -0.9551],
           [ 0.0000,  0.0000, -0.6397],
           [ 0.0000, -0.6464,  0.0000],
           [-0.0709,  0.0000, -2.0860],
           [ 0.0000,  0.0000, -0.2274],
           [ 0.0000, -1.5799,  0.0000],
           [-0.8117,  0.0000, -0.1611],
           [ 0.0000, -0.3095,  0.0000],
           [-0.3026,  0.0000, -1.0837],
           [-0.1548, -0.7543,  0.0000],
           [ 0.0000,  0.0000, -1.3297],
           [ 0.0000, -0.6601,  0.0000],
           [-0.4845, -1.3624,  0.0000],
           [ 0.0000,  0.0000, -0.5973]]]],
        [[[[ 1.2573,  0.6590, -0.2828],
           [ 1.2892,  1.1650, -2.1206],
           [ 0.8448, -0.2107, -0.3628],
           [ 1.6861,  0.6161, -2.4804],
           [ 0.4265, -0.9463,  3.1731],
           [ 0.1760, -0.2885, -0.2270],
           [ 0.6920,  1.0158, -0.9151],
           [ 0.3762, -0.9244,  4.2004],
           [ 1.0926,  1.8276, -1.8895],
           [ 1.2040,  0.6088, -0.3583],
           [ 0.8632, -0.2110, -0.5059],
           [ 0.3398, -0.5247,  4.1056],
           [ 0.0825, -0.0147, -1.3034],
           [ 1.7539,  0.8847, -2.5063],
           [-0.7149, -1.0610,  0.3214],
           [ 2.3328, -0.4350, -0.0166]],
          [[ 1.2573,  0.6590, -0.2828],
           [ 1.2892,  1.1650, -2.1206],
           [ 0.8448, -0.2107, -0.3628],
           [ 1.6861,  0.6161, -2.4804],
           [ 0.4265, -0.9463,  3.1731],
           [ 0.1760, -0.2885, -0.2270],
           [ 0.6920,  1.0158, -0.9151],
           [ 0.3762, -0.9244,  3.5490],
           [ 1.0926,  1.8276, -1.8895],
           [ 1.2040,  0.6088, -0.3583],
           [ 0.8632, -0.2110, -0.5059],
           [ 0.3398, -0.5247,  3.5490],
           [ 0.0825, -0.0147, -1.3034],
           [ 1.7539,  0.8847, -2.5063],
           [-0.7149, -1.0610,  0.3214],
           [ 2.3328, -0.4350, -0.0166]],
          [[ 1.2573,  0.6590, -0.2828],
           [ 1.2892,  1.1650, -2.1206],
           [ 0.8448, -0.2107, -0.3628],
           [ 1.6861,  0.6161, -2.4804],
           [ 0.4265, -0.9463,  3.1731],
           [ 0.1760, -0.2885, -0.2270],
           [ 0.6920,  1.0158, -0.9151],
           [ 0.3762, -0.9244,  3.5490],
           [ 1.0926,  1.8276, -1.8895],
           [ 1.2040,  0.6088, -0.3583],
           [ 0.8632, -0.2110, -0.5059],
           [ 0.3398, -0.5247,  3.5490],
           [ 0.0825, -0.0147, -1.3034],
           [ 1.7539,  0.8847, -2.5063],
           [-0.7149, -1.0610,  0.3214],
           [ 2.3328, -0.4350, -0.0166]],
          [[ 1.2573,  0.6590, -0.2828],
           [ 1.2892,  1.1650, -2.1206],
           [ 0.8448, -0.2107, -0.3628],
           [ 1.6861,  0.6161, -2.4804],
           [ 0.4265, -0.9463,  1.3315],
           [ 0.1760, -0.2885, -0.2270],
           [ 0.6920,  1.0158, -0.9151],
           [ 0.3762, -0.9244,  1.3315],
           [ 1.0926,  1.8276, -1.8895],
           [ 1.2040,  0.6088, -0.3583],
           [ 0.8632, -0.2110, -0.5059],
           [ 0.3398, -0.5247,  1.3315],
           [ 0.0825, -0.0147, -1.3034],
           [ 1.7539,  0.8847, -2.5063],
           [-0.7149, -1.0610,  0.3214],
           [ 2.3328, -0.4350, -0.0166]],
          [[ 1.2573, -0.5243, -0.2828],
           [ 1.2892, -0.5243, -2.1206],
           [ 0.8448, -0.5243, -0.3628],
           [ 1.6861, -0.5243, -2.4804],
           [ 0.4265, -0.9463,  3.1731],
           [ 0.1760, -0.5243, -0.2270],
           [ 0.6920, -0.5243, -0.9151],
           [ 0.3762, -0.9244,  3.5490],
           [ 1.0926, -0.5243, -1.8895],
           [ 1.2040, -0.5243, -0.3583],
           [ 0.8632, -0.5243, -0.5059],
           [ 0.3398, -0.5247,  3.5490],
           [ 0.0825, -0.5243, -1.3034],
           [ 1.7539, -0.5243, -2.5063],
           [-0.7149, -1.0610,  0.3214],
           [ 2.3328, -0.5243, -0.0166]],
          [[ 1.2573,  0.6590, -0.2828],
           [ 1.2892,  0.9520, -2.1206],
           [ 0.8448, -0.2107, -0.3628],
           [ 1.6861,  0.6161, -2.4804],
           [ 0.4265, -0.9463,  1.0811],
           [ 0.1760, -0.2885, -0.2270],
           [ 0.6920,  0.9520, -0.9151],
           [ 0.3762, -0.9244,  1.0811],
           [ 1.0926,  0.9520, -1.8895],
           [ 1.2040,  0.6088, -0.3583],
           [ 0.8632, -0.2110, -0.5059],
           [ 0.3398, -0.5247,  1.0811],
           [ 0.0825, -0.0147, -1.3034],
           [ 1.7539,  0.8847, -2.5063],
           [-0.7149, -1.0610,  0.3214],
           [ 2.3328, -0.4350, -0.0166]],
          [[ 1.2573,  0.6590, -0.2828],
           [ 1.2892,  0.9520, -2.1206],
           [ 0.8448, -0.2107, -0.3628],
           [ 1.6861,  0.6161, -2.4804],
           [ 0.4265, -0.9463,  1.3315],
           [ 0.1760, -0.2885, -0.2270],
           [ 0.6920,  0.9520, -0.9151],
           [ 0.3762, -0.9244,  1.3315],
           [ 1.0926,  0.9520, -1.8895],
           [ 1.2040,  0.6088, -0.3583],
           [ 0.8632, -0.2110, -0.5059],
           [ 0.3398, -0.5247,  1.3315],
           [ 0.0825, -0.0147, -1.3034],
           [ 1.7539,  0.8847, -2.5063],
           [-0.7149, -1.0610,  0.3214],
           [ 2.3328, -0.4350, -0.0166]],
          [[ 1.2573, -0.5243, -0.2828],
           [ 1.2892, -0.5243, -2.1206],
           [ 0.8448, -0.5243, -0.3628],
           [ 1.6861, -0.5243, -2.4804],
           [ 0.4265, -0.9463,  1.3315],
           [ 0.1760, -0.5243, -0.2270],
           [ 0.6920, -0.5243, -0.9151],
           [ 0.3762, -0.9244,  1.3315],
           [ 1.0926, -0.5243, -1.8895],
           [ 1.2040, -0.5243, -0.3583],
           [ 0.8632, -0.5243, -0.5059],
           [ 0.3398, -0.5247,  1.3315],
           [ 0.0825, -0.5243, -1.3034],
           [ 1.7539, -0.5243, -2.5063],
           [-0.7149, -1.0610,  0.3214],
           [ 2.3328, -0.5243, -0.0166]]]]])

In [134]:
print(upper_bounds[0])

tensor([[   inf,    inf,    inf],
        [   inf, 2.6148,    inf],
        [   inf, 2.6148, 0.4117],
        [   inf, 0.9642,    inf],
        [   inf, 0.9642, 1.4772],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


In [133]:
print(overlap_after[0][0][2])

tensor([[ 1.4000, -0.2555,  0.4117],
        [ 0.1806, -1.2344,  0.4117],
        [-0.1094,  0.5419, -0.9551],
        [ 0.8830,  0.0778, -0.6397],
        [ 0.8175, -0.6464,  0.4117],
        [-0.0709,  0.6907, -2.0860],
        [ 0.5955,  1.0229, -0.2274],
        [ 0.7555, -1.5799,  0.4117],
        [-0.8117,  1.2242, -0.1611],
        [ 1.6803, -0.3095,  0.4117],
        [-0.3026,  0.5413, -1.0837],
        [-0.1548, -0.7543,  0.4117],
        [ 0.1076,  0.0716, -1.3297],
        [ 1.0045, -0.6601,  0.4117],
        [-0.4845, -1.3624,  0.4117],
        [ 1.9982,  0.0230, -0.5973]])


In [132]:
print(overlap[0][0][0] - overlap_after[0][0][2])

tensor([[0.0000, 0.0000, 0.1620],
        [0.0000, 0.0000, 0.6886],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.1065],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 3.1015],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.3188],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 2.6142],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.1408],
        [0.0000, 0.0000, 0.9541],
        [0.0000, 0.0000, 0.0000]])


In [112]:
torch.min(objective)

tensor(-2.5063)

In [150]:
length = overlap_after - lower_bounds.view((2, 1, 8, 1, 3))
print("c",length.clamp_min(0.0)[0][0][0])

c tensor([[2.3815, 0.0000, 1.5368],
        [1.1621, 0.0000, 2.0634],
        [0.8721, 0.0000, 0.0080],
        [1.8645, 0.0000, 0.3234],
        [1.7990, 0.0000, 1.4813],
        [0.9106, 0.0000, 0.0000],
        [1.5770, 0.0000, 0.7357],
        [1.7370, 0.0000, 4.4763],
        [0.1698, 0.0000, 0.8020],
        [2.6618, 0.0000, 1.6936],
        [0.6789, 0.0000, 0.0000],
        [0.8267, 0.0000, 3.9890],
        [1.0891, 0.0000, 0.0000],
        [1.9860, 0.0000, 1.5156],
        [0.4970, 0.0000, 2.3289],
        [2.9797, 0.0000, 0.3658]])


In [151]:
length[0][0][0]

tensor([[ 2.3815, -2.8703,  1.5368],
        [ 1.1621, -3.8492,  2.0634],
        [ 0.8721, -2.0729,  0.0080],
        [ 1.8645, -2.5370,  0.3234],
        [ 1.7990, -3.2612,  1.4813],
        [ 0.9106, -1.9241, -1.1229],
        [ 1.5770, -1.5919,  0.7357],
        [ 1.7370, -4.1947,  4.4763],
        [ 0.1698, -1.3906,  0.8020],
        [ 2.6618, -2.9243,  1.6936],
        [ 0.6789, -2.0735, -0.1206],
        [ 0.8267, -3.3691,  3.9890],
        [ 1.0891, -2.5432, -0.3666],
        [ 1.9860, -3.2749,  1.5156],
        [ 0.4970, -3.9772,  2.3289],
        [ 2.9797, -2.5918,  0.3658]])

In [62]:
ref_point = [-0.9815, -0.9764, -0.9631]
hyp = pg.hypervolume(sol_df[['f1','f2','f3']].values)
hyp.compute(ref_point) #/ np.prod(ref_point)

In [53]:
obj = objective
q = obj.shape[-2]
batch_shape = obj.shape[:-2]
areas_per_segment = torch.zeros(
    *batch_shape,
    8,
    dtype=obj.dtype,
    device=obj.device,
)


In [ ]:

obj = objective
q = obj.shape[-2]
self._cache_q_subset_indices(q_out=q)
batch_shape = obj.shape[:-2]
# this is n_samples x input_batch_shape x
areas_per_segment = torch.zeros(
    *batch_shape,
    self.cell_lower_bounds.shape[-2],
    dtype=obj.dtype,
    device=obj.device,
)
cell_batch_ndim = self.cell_lower_bounds.ndim - 2
sample_batch_view_shape = torch.Size(
    [
        batch_shape[0] if cell_batch_ndim > 0 else 1,
        *[1 for _ in range(len(batch_shape) - max(cell_batch_ndim, 1))],
        *self.cell_lower_bounds.shape[1:-2],
    ]
)
view_shape = (
    *sample_batch_view_shape,
    self.cell_upper_bounds.shape[-2],
    1,
    self.cell_upper_bounds.shape[-1],
)
for i in range(1, self.q_out + 1):
    # TODO: we could use batches to compute (q choose i) and (q choose q-i)
    # simultaneously since subsets of size i and q-i have the same number of
    # elements. This would decrease the number of iterations, but increase
    # memory usage.
    q_choose_i = self.q_subset_indices[f"q_choose_{i}"]
    # this tensor is mc_samples x batch_shape x i x q_choose_i x m
    obj_subsets = obj.index_select(dim=-2, index=q_choose_i.view(-1))
    obj_subsets = obj_subsets.view(
        obj.shape[:-2] + q_choose_i.shape + obj.shape[-1:]
    )
    # since all hyperrectangles share one vertex, the opposite vertex of the
    # overlap is given by the component-wise minimum.
    # take the minimum in each subset
    overlap_vertices = obj_subsets.min(dim=-2).values
    # add batch-dim to compute area for each segment (pseudo-pareto-vertex)
    # this tensor is mc_samples x batch_shape x num_cells x q_choose_i x m
    overlap_vertices = torch.min(
        overlap_vertices.unsqueeze(-3), self.cell_upper_bounds.view(view_shape)
    )
    # substract cell lower bounds, clamp min at zero
    lengths_i = (
        overlap_vertices - self.cell_lower_bounds.view(view_shape)
    ).clamp_min(0.0)
    # take product over hyperrectangle side lengths to compute area
    # sum over all subsets of size i
    areas_i = lengths_i.prod(dim=-1)
    # if constraints are present, apply a differentiable approximation of
    # the indicator function
    if self.constraints is not None:
        feas_subsets = feas_weights.index_select(
            dim=-1, index=q_choose_i.view(-1)
        ).view(feas_weights.shape[:-1] + q_choose_i.shape)
        areas_i = areas_i * feas_subsets.unsqueeze(-3).prod(dim=-1)
    areas_i = areas_i.sum(dim=-1)
    # Using the inclusion-exclusion principle, set the sign to be positive
    # for subsets of odd sizes and negative for subsets of even size
    areas_per_segment += (-1) ** (i + 1) * areas_i
# sum over segments and average over MC samples
areas_per_segment.sum(dim=-1).mean(dim=0)